name: my-first-workflow
on: push #event of when an action gets triggered (push, pull request)concurrency

#note when there are multiple jobs, they run at the same time
jobs:
  job1:
    name: JOB1
    runs-on: ubuntu-latest
    steps:
      - name: running single command in job1
        run: echo "Hi, my name is adam"
      - name: Checking OS release of Runner
        run: cat /etc/os-release
  job2:
    name: JOB2
    runs-on: ubuntu-latest
    steps:
      - name: running single command in job1
        run: echo "Hi, my name is adam"
      - name: Checking OS release of Runner
        run: cat /etc/os-release
    
