name: my-first-workflow
on: 
  schedule:
    - cron: "5 * * * *"
  workflow_dispatch:
  push:

#note when there are multiple jobs, they run at the same time
jobs:
  jobWindows:
    name: jobWindow
    runs-on: windows-latest
    steps:
      - name: Check Runner Info
        shell: pwsh
        run: get-computerinfo
  job1:
    name: JOB1
    runs-on: ubuntu-latest
    steps:
      - name: running single command in job1
        run: echo "Hi, my name is adam"
      - name: Checking OS release of Runner
        run: cat /etc/os-release
  job2:
    name: JOB2
    runs-on: ubuntu-latest
    steps:
      - name: running single command in job1
        run: echo "Hi, my name is adam"
      - name: Checking OS release of Runner
        run: cat /etc/os-release
  job3:
      name: JOB3
      needs: job1
      runs-on: ubuntu-latest
      steps:
        - name: running single command in job1
          run: echo "Hi, my name is adam"
        - name: Checking OS release of Runner
          run: cat /etc/os-release
  job4:
        name: JOB4
        needs: [job1, job2, job3]
        runs-on: ubuntu-latest
        steps:
          - name: running single command in job1
            run: echo "Hi, my name is adam"
          - name: Checking OS release of Runner
            run: cat /etc/os-release

  actionsCheckout:
        name: actions1
        runs-on: ubuntu-latest
        steps:
          - name: firstStep
            run: |
              echo `pwd` >> myartifact.txt
              ls -ltr
              hostname
          - name: secondStep - Checkout
            uses: actions/checkout@v7.0.1
          - name: thirdStep - singleFile
            uses: actions/upload-artifact@v7.0.1
            with:
              name: single_file
              path: ./myartifact.txt
          - name: Have multiple artifacts and options (file and nondirectory)
            run: |
              mkdir artifacts
              echo `ls -ltr` >> artifacts/lists.txt
              echo `hostname` >> artifacts/hostname.txt
          #using artifacts
          - name: multiple_path_with_exclusion
            uses: actions/upload-artifact@v7.0.1
            with:
              name: Get all files and directories
              path: |
                ./myartifact.txt
                artifacts/
                !**/hostname.txt 
          #exclude
  downloadCheckout:
      name: Download Artifact
      runs-on: ubuntu-latest
      steps:
        - name: checking current dir
          run: |
            pwd
            ls -ltr
        - name: Download single file artifact
          uses: actions/download-artifact@v8.0.1
          with:
            name: single_file
        - name: checking current directory post download
          run: |
            pwd
            ls -ltr
            
          
  
            
              
            
