name: my-first-workflow
on: 
  schedule:
    - cron: "5 * * * *"
  workflow_dispatch:
  push:

#note when there are multiple jobs, they run at the same time
jobs:
  jobWindows:
    name: jobWindow
    runs-on: windows-latest
    steps:
      - name: Check Runner Info
        shell: pwsh
        run: get-computerinfo
  job1:
    name: JOB1
    runs-on: ubuntu-latest
    steps:
      - name: running single command in job1
        run: echo "Hi, my name is adam"
      - name: Checking OS release of Runner
        run: cat /etc/os-release
  job2:
    name: JOB2
    runs-on: ubuntu-latest
    steps:
      - name: running single command in job1
        run: echo "Hi, my name is adam"
      - name: Checking OS release of Runner
        run: cat /etc/os-release
  job3:
      name: JOB3
      needs: job1
      runs-on: ubuntu-latest
      steps:
        - name: running single command in job1
          run: echo "Hi, my name is adam"
        - name: Checking OS release of Runner
          run: cat /etc/os-release
  job4:
        name: JOB4
        needs: [job1, job2, job3]
        runs-on: ubuntu-latest
        steps:
          - name: running single command in job1
            run: echo "Hi, my name is adam"
          - name: Checking OS release of Runner
            run: cat /etc/os-release
